# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Edad del usuario', null=True, verbose_name='edad'),
        ),
    ]
