# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-27 23:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitacion', models.PositiveIntegerField(help_text='N\xfamero de id de la capacitaci\xf3n', verbose_name='Id Capacitaci\xf3n')),
                ('modulo', models.PositiveIntegerField(help_text='N\xfamero de id del m\xf3dulo', verbose_name='Id  M\xf3dulo')),
                ('leccion', models.PositiveIntegerField(help_text='N\xfamero de id de la lecci\xf3n', verbose_name='Id Lecci\xf3n')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avance_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Avance',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionInscrita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitacion', models.PositiveIntegerField(help_text='N\xfamero de id de la capacitaci\xf3n', verbose_name='Id Capacitaci\xf3n')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitacioninscrita_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Capacitaciones Inscritas',
            },
        ),
        migrations.AlterField(
            model_name='familiar',
            name='familiar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='familiar_familiar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
