# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20171009_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ano_aprobacion',
            field=models.PositiveSmallIntegerField(choices=[('C\xe9dula de ciudadania', 'C\xe9dula de ciudadania'), ('C\xe9dula de extranjeria', 'C\xe9dula de extranjeria'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Pasaporte', 'Pasaporte')], null=True, verbose_name='Tipos de documento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='codigo_beneficiario',
            field=models.PositiveSmallIntegerField(blank=True, help_text='C\xf3digo asignado por el PMA a sus beneficiarios', null=True, verbose_name='codigo beneficiario'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='documento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='N\xfamero de documento de identidad del usuario', null=True, verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jefe_hogar',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jefe de hogar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parentesco',
            field=models.PositiveSmallIntegerField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Otro', 'Otro')], null=True, verbose_name='Parentesco'),
        ),
    ]
