# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20171130_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='edad',
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=20, null=True),
        ),
    ]
