# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20171009_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='jefe_hogar',
            field=models.BooleanField(default=False, help_text='Determina si el usuario es el jefe de hogar', verbose_name='Jefe de hogar'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
