# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20171201_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='movil2',
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(choices=[('C\xe9dula de ciudadania', 'C\xe9dula de ciudadania'), ('C\xe9dula de extranjeria', 'C\xe9dula de extranjeria'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Pasaporte', 'Pasaporte')], max_length=45, null=True, verbose_name='Tipo de documento'),
        ),
    ]
