# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-06 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20171201_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Afrocolombianos', 'Afrocolombianos'), ('Indigenas', 'Indigenas'), ('Mestizo', 'Mestizo'), ('Otros', 'Otros'), ('Ninguno', 'Ninguno')], max_length=45, null=True),
        ),
    ]
