# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20171009_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='familiar',
            field=models.ManyToManyField(blank=True, related_name='familiar', to=settings.AUTH_USER_MODEL),
        ),
    ]
