# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-09 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20171206_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
