# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_familiar_familiar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parentesco',
        ),
        migrations.AddField(
            model_name='familiar',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Otro', 'Otro')], max_length=45, null=True, verbose_name='Parentesco'),
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='familiar',
        ),
        migrations.AddField(
            model_name='familiar',
            name='familiar',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
