# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20171009_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=45, null=True, verbose_name='Genero'),
        ),
    ]
