# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20171212_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_antiguo',
            field=models.PositiveIntegerField(blank=True, help_text='Id de la antigua base de datos', null=True, verbose_name='id antiguo'),
        ),
    ]
