# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='codigo_beneficiario',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='jefe_hogar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tipo_documento',
        ),
    ]
