# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20171010_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_beneficiario',
            field=models.PositiveIntegerField(blank=True, help_text='C\xf3digo asignado por el PMA a sus beneficiarios', null=True, verbose_name='c\xf3digo beneficiario'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comunidad',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departamento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='documento',
            field=models.PositiveIntegerField(blank=True, help_text='N\xfamero de documento de identidad del usuario', null=True, verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Edad del usuario', null=True, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='etnia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Masculino')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jefe_hogar',
            field=models.BooleanField(default=False, help_text='Determina si el usuario es el jefe de hogar', verbose_name='Jefe de hogar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='movil',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='movil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='municipio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pais',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='movil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_documento',
            field=models.CharField(choices=[('C\xe9dula de ciudadania', 'C\xe9dula de ciudadania'), ('C\xe9dula de extranjeria', 'C\xe9dula de extranjeria'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Pasaporte', 'Pasaporte')], max_length=45, null=True, verbose_name='Tipos de documento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zona',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
