# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_user_terminos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('C\xe9dula de ciudadania', 'C\xe9dula de ciudadania'), ('C\xe9dula de extranjeria', 'C\xe9dula de extranjeria'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Pasaporte', 'Pasaporte')], max_length=45, null=True, verbose_name='Tipo de documento'),
        ),
    ]
