# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_community_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('document', models.PositiveIntegerField(help_text='N\xfamero de documento de identidad del aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='TraineeAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitation', models.PositiveIntegerField(help_text='N\xfamero de id de la capacitaci\xf3n', verbose_name='Id Capacitaci\xf3n')),
                ('module', models.PositiveIntegerField(help_text='N\xfamero de id del m\xf3dulo', verbose_name='Id  M\xf3dulo')),
                ('lesson', models.PositiveIntegerField(help_text='N\xfamero de id de la lecci\xf3n', verbose_name='Id Lecci\xf3n')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainieeadvence_trainee', to='usuarios.Trainee')),
            ],
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name_plural': 'Trainings'},
        ),
        migrations.AddField(
            model_name='community',
            name='trainees',
            field=models.ManyToManyField(blank=True, to='usuarios.Trainee'),
        ),
    ]
