# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20180123_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainee',
            options={'verbose_name_plural': 'Trainees'},
        ),
        migrations.AlterModelOptions(
            name='traineeadvance',
            options={'verbose_name_plural': 'Trainees Advances'},
        ),
        migrations.AddField(
            model_name='trainee',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True, default='2018-02-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
