# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-30 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20180216_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='etnia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
