# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-13 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_user_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'es'), ('en', 'en'), ('fr', 'fr')], max_length=45, null=True, verbose_name='Idioma del usuario'),
        ),
    ]
