# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('Director', 'Director'), ('Profesor', 'Profesor'), ('Encargado del Comedor', 'Encargado del Comedor'), ('Cocinero', 'Cocinero'), ('Jefe de Cocina', 'Jefe de Cocina'), ('Comit\xe9 de Gesti\xf3n', 'Comit\xe9 de Gesti\xf3n'), ('Estudiante', 'Estudiante'), ('Otro', 'Otro')], max_length=45, null=True, verbose_name='Tipo de usuario'),
        ),
    ]
