# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_auto_20180713_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='training_role',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Trainer', 'Trainer')], max_length=45, null=True, verbose_name='Rol de capacitaci\xf3n'),
        ),
    ]
