# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_user_training_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='training_role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_trainee',
            field=models.BooleanField(default=False, help_text='For a person who did made the capacitation offline', verbose_name='Is trarinee'),
        ),
    ]
